### ISSUE TITLE
[docs] Update Contributing Guidelines

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#100]
# Issue

Currently, the [Contributing](https://github.com/AmanNegi/FreshNest/blob/main/docs/CONTRIBUTING.md) guidelines are outdated and do not provide a proper process to setup the project. It would be great if a proper step by step contribution guide could be created.

- We could perhaps break the contribution guidelines setup into 3 different files one for React, another for Node and lastly for Flutter.
- For now we should focus on Backend (node) and React.

Feel free to message to learn more about the steps that need to be involved.

**Comment by Chirayu31** [comment]
Hey would like to work on this issue. Can you assign it to me?

**Comment by AmanNegi** [comment]
Sorry, @Chirayu31 somebody was already working on the issue. Feel free to come back for new issues. ✨
