### ISSUE TITLE
Replace Agro Millets with FreshNest

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#107]
# Issue 🙈
We recently renamed our application from ~~AgroMillets~~ to **FreshNest**, however, our title bar still shows **AgroMillets**. Could you update this behavior and replace the name wherever we use the old name?

## Screenshots 📱
![image](https://github.com/AmanNegi/FreshNest/assets/37607224/ea849844-4401-4a91-ad1a-f99d8eea5484)

### Important Files 🗃

- https://github.com/AmanNegi/FreshNest/blob/main/frontend/react/index.html
- https://github.com/AmanNegi/FreshNest/blob/main/frontend/react/README.md

> Other than these feel free to search **AgroMillets* globally throughout the project.

**Comment by devr77** [comment]
@AmanNegi Would You Please Assign to me .

**Comment by AmanNegi** [comment]
@devr77 Currently I see we have received a PR from @ShubhamAXS19, so I will look into it. I will shortly add more issues, so feel free to check them out.
