### ISSUE TITLE
Add pattern data to LocalStorage

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#109]
## Issue 🙉

On the user profile page, we provide the user with the option to change the background pattern. Currently, we are storing it in the component itself, however, we now want to save it to the local device in the `AppState` Object, which is globally accessible throughout the application. The logic for storing the `AppState` object to LocalStorage is already in place, you just need to add a field of pattern to it.

![brave_Im0urJPIHa](https://github.com/AmanNegi/FreshNest/assets/37607224/e0bf94e5-3c19-4771-8280-3d6494267531)

## References 🦅

- AppState: https://github.com/AmanNegi/FreshNest/blob/main/frontend/react/src/data/AppState.js
- Profile Page: https://github.com/AmanNegi/FreshNest/blob/dad33b825a067c16b2067181f6d54d594ba78de4/frontend/react/src/pages/Profile/presentation/Profile.jsx#L17C25-L17C25

> Feel free to comment and ask if you have any queries.

**Comment by Rhythm-08** [comment]
I would like to work on this issue

**Comment by AmanNegi** [comment]
Sure @Rhythm-08. Let me know if you face some issue while setting up.

**Comment by AmanNegi** [comment]
Fixed by #111
