### ISSUE TITLE
[docs] Update React Configuration in CONTRIBUTING.md

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#115]
# Issue:

Currently, we do have a `CONTRIBUTING.md` however it does not specify in detail how to set up the React Part of the application and run it in the local system. It would be nice to have, an extensive guide that could help new contributors.

- https://github.com/AmanNegi/FreshNest/blob/dev-react/docs/CONTRIBUTING.md
- https://github.com/AmanNegi/FreshNest/tree/main/frontend/react#readme

**Comment by Rhythm-08** [comment]
Hello, I would like to take this issue

**Comment by AmanNegi** [comment]
Fixed by #117.
