### ISSUE TITLE
Improve cards design in large screen

### ISSUE THREAD

**Issue by FabianCristancho** [AmanNegi/FreshNest#116]
I noticed that when you view the page on a large screen the cards in the "Our User Review" section are not being centered, so this affects the layout of the page.

![image](https://github.com/AmanNegi/FreshNest/assets/37461628/c88ec26b-1a31-4c1c-9aae-f48c0f6efb20)

Please let me work on this issue to participate in HacktoberFest.

**Comment by AmanNegi** [comment]
I really appreciate your efforts @FabianCristancho.

This is really embarassing but I noticed that we had wrong link placed in Readme.md. I have now updated the link, could you please check it out and suggest some improvements in that.
