### ISSUE TITLE
Implement Client-Side Filtering for Shop Page

### ISSUE THREAD

**Issue by Chirayu31** [AmanNegi/FreshNest#121]
The current Shop page fetches data from the server every time a user selects a filter, resulting in unnecessary API calls and slower performance. To optimize performance and reduce server load, we should transition to client-side filtering.

**Proposed Solution:**

1. Fetching all necessary data from the server on the initial page load.
2. Implementing client-side filtering to instantly update displayed products when users select filter options.
3. Offering an option for users to refresh data from the server when needed.

Implementing client-side filtering will greatly enhance Shop page performance, creating a more efficient and user-friendly experience

**Comment by AmanNegi** [comment]
Great observation @Chirayu31! That should exponentially increase the performance. Feel free to drop a PR if you're interested in working on this issue. 😄

**Comment by Chirayu31** [comment]
Working on it!
