### ISSUE TITLE
Suspense for Login/SignUp Page

### ISSUE THREAD

**Issue by ayobamiseun** [AmanNegi/FreshNest#123]
We can add loading to the Login button  to indicate that a request is being processed and also disable any actions to prevent multiple requests from being created.

**Comment by AmanNegi** [comment]
Nice, observation @ayobamiseun. This could be further extended to the SignUp Page as well.

**Comment by ayobamiseun** [comment]
You can assign it to me.

**Comment by AmanNegi** [comment]
Sure, let me know if you have some trouble setting up!

**Comment by ayobamiseun** [comment]
done with the update

**Comment by AmanNegi** [comment]
@ayobamiseun Seems like you forgot to push the code.
