### ISSUE TITLE
[BUG]: Add Email and Password Validation to Login/SignUp Page

### ISSUE THREAD

**Issue by sumit639-code** [AmanNegi/FreshNest#125]
![image](https://github.com/AmanNegi/FreshNest/assets/63084040/6671dc3c-05e3-496a-afe3-9fe82dfb7806)

It dosent check the text to get the right email and password.

**Comment by AmanNegi** [comment]
@sumit639-code We could further extend it to the SignUp Page as well. Feel free to let me know if you're interested to work on this issue.

**Comment by sumit639-code** [comment]
Afcourse i want to work on this.

**Comment by AmanNegi** [comment]
Great! Let me know if you have any trouble setting up the project.

**Comment by sumit639-code** [comment]
I want to run the project in my system but its telling my your package file is not there

**Comment by AmanNegi** [comment]
Did you follow the setup guide: https://github.com/AmanNegi/FreshNest/blob/main/frontend/react/README.md

**Comment by sumit639-code** [comment]
Yes i added an .env file but didnt work

**Comment by AmanNegi** [comment]
Did you run `npm install`? If it still doesn't work simply install `vite` as a global package.
```js
npm install -g vite
```

**Comment by sumit639-code** [comment]
Thank you, It worked

**Comment by AmanNegi** [comment]
@sumit639-code any updates on this issue?

**Comment by sumit639-code** [comment]
yes currently working on it

**Comment by sumit639-code** [comment]
Yes done 
but i dont knwo why this is showing
![image](https://github.com/AmanNegi/FreshNest/assets/63084040/171da445-9104-4496-8416-61d904dc0d77)

**Comment by AmanNegi** [comment]
Can you ensure you are on the right branch, and sync the lastest changes with the main branch.

**Comment by sumit639-code** [comment]
yes i pushed the update in the main branch

**Comment by AmanNegi** [comment]
Hey @sumit639-code, you are not supposed to push to `main` branch directly. Check out these tutorials on how to fork, create a branch, and then make changes, commit, and push changes.

- https://opensource.guide/how-to-contribute/#opening-a-pull-request
- https://github.com/firstcontributions/first-contributions#create-a-branch

**Comment by sumit639-code** [comment]
i have created a new branch and then i have created the change but then only the error is showing

**Comment by sumit639-code** [comment]
log-check

**Comment by AmanNegi** [comment]
You need to pull in the changes before pushing anything, as your branch is 200+ commits behind.
