### ISSUE TITLE
Effects in Our gallery and features section

### ISSUE THREAD

**Issue by harshsbhandari** [AmanNegi/FreshNest#131]
Our gallery and Our features container hover effect and they don't redirect to some another page. Can I remove the hover effect and add some gradient effect for the same @AmanNegi

**Comment by AmanNegi** [comment]
@harshsbhandari What do you specifically mean by gradient effect here?

**Comment by harshsbhandari** [comment]
Somethibg like this - https://www.google.com/search?q=on+hover+remove+gradient+effect+gif&tbm=isch&ved=2ahUKEwim-fXWoeOBAxVyamwGHbwfDQIQ2-cCegQIABAA&oq=on+hover+remove+gradient+effect+gif&gs_lcp=CgNpbWcQA1C4AliCGmC3HWgBcAB4AIABpQGIAbEHkgEDMC42mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=gfQgZea0IPLUseMPvL-0EA&bih=707&biw=1519&rlz=1C1JJTC_enIN968IN968&hl=en#imgrc=WsymSl8tiPwqVM

**Comment by AmanNegi** [comment]
I'm not sure if that would work well with images. Let me know if I'm missing something here.

**Comment by harshsbhandari** [comment]
let me give it a try

**Comment by harshsbhandari** [comment]
can you please this label as hacktoberfest

**Comment by AmanNegi** [comment]
@harshsbhandari This repository is marked as `hacktoberfest`, so any PR that gets merged will be counted in `hacktoberfest`. As soon as I'm sure that this issue needs to be worked on, I will add it to the Project and the labels will be allotted.

**Comment by harshsbhandari** [comment]
can i work on it ?

**Comment by AmanNegi** [comment]
Sure give it a try, if it looks better.

**Comment by harshsbhandari** [comment]
Unable to run backend code locally, can you help me with it

**Comment by AmanNegi** [comment]
Share the problems you are facing with relevant screenshots or logs.

**Comment by harshsbhandari** [comment]
I can run the frontend on my machine locally - 
![Screenshot (141)](https://github.com/AmanNegi/FreshNest/assets/73375087/d51bf46c-5bb0-46fc-9302-23ac812213f0)
I need something to bypass this login page. I tried to run the backend on my machine this is what i get - 
![Screenshot (142)](https://github.com/AmanNegi/FreshNest/assets/73375087/cf95dc00-adc9-4258-beab-a1c950f53585)

**Comment by AmanNegi** [comment]
Did you checkout how to setup guide?
https://github.com/AmanNegi/FreshNest/tree/main/backend#readme
