### ISSUE TITLE
Explore the products image parts cuts off

### ISSUE THREAD

**Issue by Codensity30** [AmanNegi/FreshNest#133]
![image](https://github.com/AmanNegi/FreshNest/assets/129579058/9e0ed7c0-22e4-493d-a193-3213dac2635a)

I think currently the text "Explore out products" is written on the image itself that's the reason the text is not responsive.
If we cast text over the image that could solve the issue.

I'm interested in contributing, let me know if I should start.

**Comment by AmanNegi** [comment]
@Codensity30 Thanks for observing the issue. You are right, we should definitely use text over the image so that the layout remains responsive. Feel free to setup and explore the codebase, while I provide you the background image.

**Comment by AmanNegi** [comment]
[Here's](https://github.com/AmanNegi/FreshNest/assets/37607224/2b47ed64-3746-4807-8ca8-b542da34d893) the background image without any text:

**Comment by Codensity30** [comment]
Thanks for providing the background image. Now, I have started working on it and will open PR very soon.

**Comment by Codensity30** [comment]
what should be to font for "Explore our" and "Products"? shall I let this be the default one or it should be the same as the image, there is no need to import 2 fonts just for two words.

**Comment by AmanNegi** [comment]
Yeah using the default font seems ideal to me. 👍

**Comment by AmanNegi** [comment]
Fixed by #135.
