### ISSUE TITLE
Documentation Update: Clarify FreshNest's Purpose as a Learning Codebase

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#134]
## Issue Overview:
The current documentation for FreshNest gives the impression that we are a brand competing in the eCommerce market. However, our actual purpose is quite different. FreshNest is a full-stack e-commerce application created to serve as a perfect codebase for learning and practice, rather than as a commercial enterprise. This issue aims to address the mismatch between the current documentation and our true purpose.

## Scope:
This issue will focus on updating the project documentation to ensure that it accurately reflects FreshNest's role as a full-stack e-commerce application designed primarily for educational purposes. We want to eliminate any potential confusion regarding our project's objectives.

## Proposed Changes:
- [ ] Revise the project's README to emphasize our educational mission.
- [ ] Add a subsection that highlights FreshNest's role as a codebase for new developers.
- [ ] Clarify that FreshNest is not intended for commercial use but is meant for learning and practice.
- [ ] Additionally, add a section that addresses the question: "Why build it if it is not actively used in the real world?"
- [ ] Provide links to relevant resources or documentation for new contributors to get started.

## Expected Impact:
By addressing this issue, we aim to align our documentation with FreshNest's true purpose, reducing any potential misconceptions about our project's goals. This will create a more suitable learning environment for those interested in using FreshNest for skill development.

**Comment by Chirayu31** [comment]
Would like to work on this

**Comment by AmanNegi** [comment]
Sure @Chirayu31 you can get started, Let me know if you need more clarification on the changes.
