### ISSUE TITLE
React: Finish and improve AddItem Page

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#139]
## Issue

When we log in as a farmer, we get the option to add a new item from the shop page. However, the layout is shabby and does not use the `DaisyUI` components.  This issue would include the following:

- [ ] Usage of DaisyUI Components for the Input Fields, File Picker and Buttons
- [ ] Making requests to the backend to add items, with required fields.

## Additional Details

1. Set up the project as mentioned, it is preferable to use the Local Server. [Check This](https://github.com/AmanNegi/FreshNest/blob/main/backend/README.md).
2. Now that your local server is started, it's time to get started with the front end. [Check This](https://github.com/AmanNegi/FreshNest/blob/main/frontend/react/README.md).
3. Sign up as `Farmer` and go to the shop and try to add an item.
4. You are now on the AddItem Page.

### Backend APIs to be used

   - https://github.com/AmanNegi/FreshNest/blob/ce8d1ea02d8edc6906a82f8be88889a4a02a58f3/backend/routes/list.js#L46 
   - https://github.com/AmanNegi/FreshNest/blob/ce8d1ea02d8edc6906a82f8be88889a4a02a58f3/backend/models/millet_item.js#L40

**Comment by lapso222** [comment]
hi, could you assign me this issue please?

**Comment by AmanNegi** [comment]
Sure get started, let me know if you have some issues setting up.

**Comment by AmanNegi** [comment]
@lapso222 Sorry but, this issue is already taken.

**Comment by AmanNegi** [comment]
@lapso222 Feel free to get started! Let me know if you have any trouble setting up the project.

**Comment by lapso222** [comment]
Can you please provide acceptance criteria for this issue. Thank you.

**Comment by AmanNegi** [comment]
Acceptance criteria is implementing the complete scope of the issue, as described above in Issue Description.

**Comment by lapso222** [comment]
Ok then, i will work on this

**Comment by Sandesh-03** [comment]
hey, can I try?

**Comment by lapso222** [comment]
> hey, can I try?

Hi i am working on this, i have this issue already assigned, i need this for my school project to be done so dont worry i will make it 😉

**Comment by Sandesh-03** [comment]
> > hey, can I try?
> 
> Hi i am working on this, i have this issue already assigned, i need this for my school project to be done so dont worry i will make it 😉

okay 👍

**Comment by dipaksinha1** [comment]
Hi @MartinLapsansky ,

Are you still investigating this issue? If not, I would like to request @AmanNegi to please assign me this issue.

Thank you

**Comment by AmanNegi** [comment]
@dipaksinha1 Seems like @MartinLapsansky is not working on this issue now. Let me know if you are still interested in working on this issue. 😊

**Comment by dipaksinha1** [comment]
Hi @AmanNegi ,
Sure, You can assign me this issue.

**Comment by AmanNegi** [comment]
Sure, feel free to get started!
