### ISSUE TITLE
content stretching on 4k screen sign-up and login

### ISSUE THREAD

**Issue by ayobamiseun** [AmanNegi/FreshNest#141]
### On 4K screens, the Sign Up and Login pages exhibit design issues:

1. **Page Stretching:**
The content on these pages extends too far horizontally, causing user experience problems. 

2. **Logo Alignment:**
The Sign Up page logo is misaligned with other elements, impacting the design.

**Comment by AmanNegi** [comment]
@ayobamiseun Could you add screenshots to support this issue.

**Comment by ayobamiseun** [comment]
<img width="1292" alt="Screenshot 2023-10-12 at 08 19 32" src="https://github.com/AmanNegi/FreshNest/assets/66267222/318eaf27-62d8-4e0d-b1cf-c87d169d003e">
<img width="239" alt="Screenshot 2023-10-12 at 08 20 29" src="https://github.com/AmanNegi/FreshNest/assets/66267222/379b8eee-24f8-46a2-a2c0-b97f06ba014c">
 text is too stretch on 2000plus screen size

**Comment by AmanNegi** [comment]
How do you plan to fix this issue? If this happens in the Auth Pages, I'm certain it happens in all other pages as well.

**Comment by ayobamiseun** [comment]
@AmanNegi By setting a max-width.

**Comment by AmanNegi** [comment]
Could you make the suggested changes and provide a before and after comparison. (of login/signup)

**Comment by ayobamiseun** [comment]
> Could you make the suggested changes and provide a before and after comparison. (of login/signup)

<img width="1276" alt="Screenshot 2023-10-13 at 07 38 16 1" src="https://github.com/AmanNegi/FreshNest/assets/66267222/020ef0d5-30f2-4d00-8895-4237e38817e5">
you can see in the case of LinkedIn everything is centralised with margin on both side on large screen instead of stretching across the screen.

**Comment by AmanNegi** [comment]
That seems nice feel free to make these changes.

**Comment by dipaksinha1** [comment]
HI @AmanNegi ,

Can you assign this issue to me as it is not assigned to anyone yet?

Thank you

**Comment by AmanNegi** [comment]
Sure @dipaksinha1 feel free to raise a PR with requested changes.

**Comment by dipaksinha1** [comment]
here is the PR #160

**Comment by AmanNegi** [comment]
Fixed by #160.
