### ISSUE TITLE
flutter: Add View Image in FullScreen Page

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#144]
## Feature:

When we open a product detail page, we get a cropped image of the product. We should provide a feature where the user can hold on to the image to view it in its original aspect ratio. 

#### Product Detail Page
![Screenshot_2023-05-01-10-46-09-25_81c0b6ec763509e489537c6b7ee13a9e 2](https://github.com/AmanNegi/FreshNest/assets/37607224/117f139c-2520-4877-ac64-9701072684e1)
---
 If the user clicks and holds on the image, we can either show the image on a separate page in fullscreen or simply show it as an overlay. Feel free to discuss which behavior you plan to implement before getting started.

**Comment by Summiedev** [comment]
Can u assign this to me? I'll implement it as an overlay

**Comment by vishal-sharma-369** [comment]
Please assign this issue to me.

**Comment by AmanNegi** [comment]
@vishal-sharma-369 feel free to create a new issue for the web implementation. This issue is specifically created for the Mobile version.

**Comment by AmanNegi** [comment]
@Summiedev Feel free to get started with this issue, let me know if you need any help setting up.

**Comment by Sandesh-03** [comment]
please assign this to me

**Comment by AmanNegi** [comment]
@Sandesh-03 as you can see it's already assigned. I will be adding more issues so, feel free to check other issues.

**Comment by Summiedev** [comment]
> @Summiedev Feel free to get started with this issue, let me know if you need any help setting up.

I'm sorry, I've unassigned myself bcos laptop is currently broken and it's going to take awhile to get fixed

**Comment by NishchayShakya1** [comment]
> @Sandesh-03 as you can see it's already assigned. I will be adding more issues so, feel free to check other issues.

I have added this feature to my PR #156 . please check it.

**Comment by NishchayShakya1** [comment]
I have implemented all the necessary features.
Please check my PR - https://github.com/AmanNegi/FreshNest/pull/156
