### ISSUE TITLE
React: Fix Spacing Issue in Update Details Dialog

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#145]
## Issue

The spacing between fields doesn't seem equal, especially if we look above the phone label. 

![image](https://github.com/AmanNegi/FreshNest/assets/37607224/6a069377-fd19-4c41-a0dc-59c7d989681a)

## How to Reproduce?
1. Go through our [Contributing Guidelines](https://github.com/AmanNegi/FreshNest/blob/main/docs/CONTRIBUTING.md) and setup your project. Set the environment to the remote development server.
2. Go to your localhost, and log in using the below credentials:
> email: **customer@gmail.com** password: **password**
3. Go to the user page, and from settings click on Edit Profile. You have now successfully opened the dialog.

**Comment by Yasir761** [comment]
Can u assign this to me?

**Comment by AmanNegi** [comment]
Sure! Let me know if you need help with something.

**Comment by kulkarnikedar** [comment]
Just Check  by  updating  below change in the FreshNest\frontend\react\src\pages\Profile\presentation\UpdateModal.jsx file 
    
     <div className="flex flex-col **mt-2**">
          <label htmlFor="input">Phone</label>
          <input
            name="phone"
            onChange={handleFieldChange}
            value={data.phone}
            type="phone"
            className="input input-bordered mt-2"
          ></input>
        </div>
