### ISSUE TITLE
flutter: Add pull to refresh on Shop Page

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#150]
## Feature

Add pull-to-refresh on the Shop Page, so that the user can reload/refreshes the items as he wishes and the new data is shown.

![Screenshot_2023-10-16-06-46-33-05_c69b77f375e52fba4e48b6056cb57593.jpg](https://github.com/AmanNegi/FreshNest/assets/37607224/def43fac-e59d-4ef6-a72d-21ce41f9c251)

**Comment by Sandesh-03** [comment]
Hey @AmanNegi  can I do this ?

**Comment by AmanNegi** [comment]
Sure @Sandesh-03. Feel free to get started.

**Comment by AmanNegi** [comment]
@Sandesh-03 Any updates on this?

**Comment by Sandesh-03** [comment]
I am working on this.
