### ISSUE TITLE
React: Convert email to lowercase before attempting Auth

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#151]
## Issue
When we try to log in using email, it takes case-sensitive emails which is not expected, this is similar across SignUp as well. There's no need for case-sensitive emails, so convert it to lowercase as we keep on getting input. 

## Screenshots
![Screenshot from 2023-10-17 11-47-01](https://github.com/AmanNegi/FreshNest/assets/37607224/454e70ff-7fd5-40da-842c-596eb22ba03d)

## References:

- https://github.com/AmanNegi/FreshNest/blob/bdf549c178eb87077a9221141538ef34424656be/frontend/react/src/pages/Auth/presentation/Login.jsx#L80
- https://github.com/AmanNegi/FreshNest/blob/main/frontend/react/src/pages/Auth/presentation/SignUp.jsx

**Comment by ShimanshuChauhan** [comment]
Hey @AmanNegi  Can you please assign it to me.

**Comment by AmanNegi** [comment]
Sure feel free to get started!
