### ISSUE TITLE
doc: Update `.env` setup in React Setup Docs

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#153]
## Issue

Currently in out React Setup Guide, we don't inform the user about the `GLogin` environment variables, which he can put in his `.env` files. Add a step by step guide on how to generate the `GLogin` credentials, and add it to the `.env` file.

### References:

- Add steps [here](https://github.com/AmanNegi/FreshNest/blob/main/frontend/react/README.md#want-to-use-googlelogin-on-local-dev-server).
- Find all the GLogin related environment variables [here](https://github.com/AmanNegi/FreshNest/blob/9b974900fb50da02ab91c65ce460c97fe889c2fa/frontend/react/src/main.jsx#L71).

**Comment by H-SM** [comment]
hey @AmanNegi, I would like to work over this issue.. Have a great day

**Comment by AmanNegi** [comment]
Feel free to get started, let me know if you have any trouble. Also love, your profile animation (hsm), would love to know how you created it. :D

**Comment by H-SM** [comment]
ayo @AmanNegi , thanks for assigning it up, ill start it up tonight (hopefully even finishing it up...). For the profile animation, I created it using Photoshop & illustrator and I animated it using after effect, it's no biggy I was just learning to make animated GIFs, found it as an opportunity. Thanks for noticing my work there ... 👀😊
