### ISSUE TITLE
UI: Give Breathing Space to all UI Layouts

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#171]
![image](https://github.com/AmanNegi/FreshNest/assets/37607224/b9f28b2d-cba5-4dfd-aef9-7ab0c38107b2)

**Comment by harshsrivastav8055** [comment]
Can you please assign me this issue

**Comment by AmanNegi** [comment]
@harshsrivastav8055, I would like to inform you that the current issue is not designated as `help-wanted`, hence, I am unable to assign it to you. It's worth noting that the repository is presently undergoing substantial changes.

I would like to kindly suggest checking back at a later time. I am confident that there will be forthcoming issues where your assistance would be highly valuable.
