### ISSUE TITLE
Chore: Add PropTypes to components in React

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#177]
## Issue Description

Currently, we do have the `prop-types` imported in our package.json however we do not use it to define the prop types for our components. It would be nice & type safe, if they could be added for each component.

- All Components can be found under `/src/components`.
- All Pages can be found under `/src/pages`.

> It's possible that if the PR gets too large this can be divided into two separate PR's.

**Comment by Saran-pariyar** [comment]
I want to do it. 

Should I start adding propType like this in every component and page? Anything other that I should consider? Thanks.

![image](https://github.com/AmanNegi/FreshNest/assets/86418083/7b527643-ae35-4de4-acdf-ea7bf74ea03f)

**Comment by AmanNegi** [comment]
Sure, @Saran-pariyar Welcome to FreshNest. Yes that's exactly what we want to do, you will find the places where prop-types as errors through `eslint`. 

```npm run lint```

This will list all the places where `prop-types` are needed. Let me know if something else is needed. :sparkles: :smile:

**Comment by AmanNegi** [comment]
Fixed via https://github.com/AmanNegi/FreshNest/pull/197
