### ISSUE TITLE
fix: remove timer's live property

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#185]
## Description 🤷‍♂️

After adding a product as a farmer, we are redirected to the home page. On the home page, we see a grid of items with the time they were added. However, the newly added item shows a live timer such as "1, 2, 3 seconds ago" which is unexpected and seems like an error.

We want to remove the live behaviour of the time shown.

### Demo 📽️

https://github.com/AmanNegi/FreshNest/assets/37607224/7fb7239f-5b60-470a-876d-2db8160ae2ad

### Affected Files 🗃️

- frontend/react/src/components/ShopItem.jsx

**Comment by MohitKambli** [comment]
Hello @AmanNegi,
Hope you're doing well.
I would like to work on this issue.
Firstly, Is this how the cart should look like?

![image](https://github.com/AmanNegi/FreshNest/assets/31406633/a084c080-5f20-4060-aa4d-b86d1c15d5cb)

Secondly, for some reason, I am not able to login neither as a customer nor as a farmer.
All I am able to see is something like this:

![image](https://github.com/AmanNegi/FreshNest/assets/31406633/a0b5d4e8-b740-42d9-a762-f48c4a64bc2c)

Do you think I did something wrong while implementing the above steps?
According to the documentation, I did these [steps](https://github.com/AmanNegi/FreshNest/blob/main/frontend/react/README.md#steps-%EF%B8%8F).

My .env file has the following line as of now:
`VITE_API_URL="https://agromillets.adaptable.app/api"`

My node version is:
`v18.18.0`

Thanks and Regards,
Mohit Kambli

**Comment by AmanNegi** [comment]
Thank you for investigating the problem, @MohitKambli. It appears that the profile page was causing issues due to a react query cache problem. However, I have fixed the issue now. Please pull from the main branch and use the credentials provided below to log in as a farmer.

```js
email: farmer@gmail.com
password: password
```

**Comment by MohitKambli** [comment]
Hello @AmanNegi,
Hope you're doing well.
Thank you for your assistance and crisp explanation.
Now, I am successfully able to login as a farmer and customer as well.
So, on making the code changes for removing the time, this is how the farmer page looks like:

![image](https://github.com/AmanNegi/FreshNest/assets/31406633/be86128d-71ab-4e55-a228-29ff020ec419)

This is how the customer page looks like:

![image](https://github.com/AmanNegi/FreshNest/assets/31406633/38faf701-4190-4eb6-87f7-1c75dcbf81da)

Do you think the above changes satisfy the requirements?
If at all there's any issue from my end, then do let me know.
Sincere apologies for my mistakes if you find any.
I will raise a PR for the same in some time.
Thank you so much for your understanding and assistance

Thanks and Regards,
Mohit Kambli

**Comment by AmanNegi** [comment]
@MohitKambli Sorry but removing the timer is not the purpose of this issue. We actually, want to remove the live behavior that we see as I have shown in the issue description. Sorry that the description was not clear enough.  What we want is that the timer should just stay and not get updated in realtime. Like it does currently, when we add an item. 

I will also update the details accordingly, so that it's more clear.

**Comment by MohitKambli** [comment]
Hello @AmanNegi,
Sincere apologies for not understanding the issue quite correctly.
I sort of misunderstood the requirement.
So, I was trying to add an item from my end, but this is what I get while adding an item.

![image](https://github.com/AmanNegi/FreshNest/assets/31406633/7422b79e-be33-4aec-b62c-774f8b36d4bb)

Could you please help me in resolving this issue?

Thanks and Regards,
Mohit Kambli

**Comment by AmanNegi** [comment]
@MohitKambli The firebase storage requires you to first set all the .env variables as mentioned below in `main.jsx`. To get these credentials you can simply go to `firebase.google.com` and create a project and get these credentials.

```
// main.jsx
const app = initializeApp({
  apiKey: import.meta.env.VITE_API_KEY,
  authDomain: import.meta.env.VITE_AUTH_DOMAIN,
  projectId: import.meta.env.VITE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_APP_ID,
  measurementId: import.meta.env.VITE_MEASUREMENT_ID
});
```

Simply go to Firebase console, spin a new project, click on add a new app select web and you'll get the below page with credentials:

![image](https://github.com/AmanNegi/FreshNest/assets/37607224/55291dec-f9b4-49d8-a290-168417ca224f)
> Save these we'll need them later

Next, go back to the project page, and go under `build -> firebase storage`. Enable the Firebase storage in test mode, and select any region server to continue. You're good to go now! ✨🚀

Simply add the creds you got earlier into `.env` file as annotated in `main.jsx`:
```.env
VITE_API_KEY="your_key_here",
// ... so on
```

**Comment by AmanNegi** [comment]
@MohitKambli There's no need to do that I believe, check this out I found this in `react-timeago` library:

- https://github.com/nmn/react-timeago?tab=readme-ov-file#live-optional

This resolves our issue of live timer, could you add the optional parameter to all places where `react-timeago` is used.

**Comment by MohitKambli** [comment]
Hello @AmanNegi,
Awesome.
Thank you so much for informing.
Should've checked the documentation for this.
Sincere apologies for this.
I checked the code base.
I am able to see only this file _**(frontend\react\src\components\ShopItem.jsx)**_ where the `react-timeago` has been used.
So now, this is how the code would look like

```
<div className="bg-gray-200 inline-flex flex-row mx-2 items-center justify-start px-3 gap-3 py-1 rounded-[5px] text-xs ">
  <FaClockRotateLeft />
  <TimeAgo date={item.listedAt} live={false} />
</div> 
```

I guess this would help in meeting the necessary requirements, right?
Sincere apologies for my mistakes.
If at all you think this looks fine, then I'll raise a PR for the same.

Thanks and Regards,
Mohit Kambli
