### ISSUE TITLE
fix: Round off the price at item detail page currently it shows elongated price

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#186]
## Issue Description 🕊️

On the item detail page, the price should be displayed in a more visually pleasing format, rounded to two decimal places.

## References 🗃️
![image](https://github.com/AmanNegi/FreshNest/assets/37607224/b933be14-8817-4970-a627-78f93b63e2db)

**Comment by Shoaib-2** [comment]
Hey @AmanNegi, I want to contribute to this issue. But I am struggling to find codebase. Possibly, this is my first open source contribution. If you can help me around this, then I am pretty sure I can fix this issue.

**Comment by MohitKambli** [comment]
> Hey @AmanNegi, I want to contribute to this issue. But I am struggling to find codebase. Possibly, this is my first open source contribution. If you can help me around this, then I am pretty sure I can fix this issue.

Hello @Shoaib-2,
Hope you're doing well.
Normally, you find the codebase of any project under the **_Code_** section. You can see it over here:

![image](https://github.com/AmanNegi/FreshNest/assets/31406633/a9fa5ca2-458e-40e8-a4a3-807e790134f6)

Hope that helps you.

**Comment by AmanNegi** [comment]
@Shoaib-2 As Mohit mentioned above you can find the code on the home page of the FreshNest repo. You can then Fork the Repo and continue making changes. I would suggest that you take a tutorial before starting.

- https://youtu.be/apGV9Kg7ics?si=qchaP453IoJpGMP3
- https://opensource.guide/

Also, all open-source repositories have a [`CONTRIBUTING.md`](https://github.com/AmanNegi/FreshNest/blob/main/docs/CONTRIBUTING.md) which can assist with most of the questions you might have related to contributing.

It appears that @MohitKambli has solved this issue, however, it's always a good idea to get assigned first and then raise a PR. Please feel free to set up and explore the project. Keep an eye on the issues tab as new ones are added regularly. 

> Let me know if you have any more queries I will keep this issue open for a while.🤗

**Comment by Shoaib-2** [comment]
Hello @AmanNegi and @MohitKambli , I am so sorry for that. Thank you for letting me know. I’ll surely watch a tutorial and get back doing things. Thank you so much for the insights. Well, I’ll definitely keep a watch and raise a PR accordingly.

**Comment by AmanNegi** [comment]
Great @Shoaib-2, If you have any issues during the setup phase feel free to create an issue. I'll be happy to assist you 🤗

**Comment by Shoaib-2** [comment]
@AmanNegi Surely. Glad to hear that
