### ISSUE TITLE
[Bug]: Docs Update

### ISSUE THREAD

**Issue by mohit-bhandari45** [AmanNegi/FreshNest#198]
**Describe the bug**
@AmanNegi is there any requirement of updating docs for the contributors for locally setting up the project Freshnest?
I can work on that, if required. Otherwise you can close the issue.

**To Reproduce**
1. Just go through the docs

**Expected behavior**
The readme file should tell contributors, how to setup the project locally.

**Comment by AmanNegi** [comment]
Hello @mohit-bhandari45 thanks for offering the assistance. However, we already do have contribution documentation for beginner contributors. 

- https://github.com/AmanNegi/FreshNest/blob/main/docs/CONTRIBUTING.md

We also do already have per-platform documentations:

- Backend: https://github.com/AmanNegi/FreshNest/blob/main/backend/README.md
- Web Client: https://github.com/AmanNegi/FreshNest/blob/main/frontend/react/README.md
- Mobile Client: https://github.com/AmanNegi/FreshNest/blob/main/frontend/flutter/README.md

If you want to offer any updates to these docs or wish to add few more points which enhance the setup process, you are more than welcome! Any issues that you came through while setting up could be an helpful increment to these docs.

**Comment by mohit-bhandari45** [comment]
Ok sure, sorry I didn't noticed that.
You can close the issue.
