### ISSUE TITLE
[React] Fix ShopItem Mobile Layout

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#78]
# Issue

The layout of shop items gets skewed on the Shop Item Page. Use appropriate TailwindCSS to ensure the page looks great on mobile devices as well.

## Files to be changed

`fronted/react/src/pages/shop/presentation/ItemDetail.jsx`
> This is just provided for simplicity of navigation and reference. If required more files can be affected according to needs.

## Screenshots

![Image](https://user-images.githubusercontent.com/37607224/247929351-8bb6df33-c413-4a7b-9aa3-3f0db3a2b629.png)

**Comment by vinayakGarudi2002** [comment]
Hello Sir,
We would like to contribute to this issue. Please assign it to us. ( We are Engineering Students and Compulsorily required to contribute to open source. Thus You can expect a good fix to the issue) 

Thank You
@vinayakGarudi2002
@v-i-v-e-k-01

**Comment by AmanNegi** [comment]
Sure, @vinayakGarudi2002 feel free to make the changes and make a PR. Let me know if you're facing some issues settings up. Here's a recent guide I provided in a PR: https://github.com/AmanNegi/FreshNest/issues/77#issuecomment-1628418222.

**Comment by vinayakGarudi2002** [comment]
Okay Thank you

**Comment by vinayakGarudi2002** [comment]
Hello Sir , 
We are Studying the repository and the work will be completed by  the end of this semester i.e by October end. Please do tell if it is not feasible for you. 
We are planing to complete it before october itself

**Comment by AmanNegi** [comment]
@vinayakGarudi2002 No updates on this?

**Comment by cheesequake** [comment]
@AmanNegi could you please tell me how to run it locally? After "npm install" i put "npm run dev", causing it to start locally, but I am unable to get past the login page. If I change the URL by adding a "/shop" after it, the products do not load, they just shimmer. I added the "VITE_API_URL" in a .env file as well, but that didn't seem to work.

**Comment by AmanNegi** [comment]
Thanks for the detailed message @cheesequake. Here are a few things I have to say:

1. Use Node Version [`v18.14.0`](https://nodejs.org/dist/v18.4.0/).
2. After this you will need to clear your old `node_modules` and run `npm install` again.
3. After that, you should be able to run the front end.
> Note you would not be able to upload images or use Google SignIn because those need separate keys for those configs.

Don't forget to set the `.env` file:
```env
VITE_API_URL="https://agromillets.adaptable.app/api"
```

**Comment by cheesequake** [comment]
@AmanNegi Thank you for the reply. I have made changes and created a pull request for the same. Kindly check and let me know about the same :)

**Comment by AmanNegi** [comment]
Fixed via #113.
